// <auto-generated />
using EmptyCoreWebApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmptyCoreWebApplication.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("EmptyCoreWebApplication.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "English 101: Introduction to Language Learning is designed for students who are beginning their journey in mastering the English language. This course focuses on developing foundational skills in reading, writing, listening, and speaking.",
                            Price = 500m,
                            ProductName = "English 101"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "English 201: Intermediate Language Learning is designed for students who have a foundational knowledge of English and seek to further develop their language skills. This course focuses on enhancing proficiency in reading, writing, listening, and speaking at an intermediate level.",
                            Price = 600m,
                            ProductName = "English 201"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "English 301: Advanced Language Learning is designed for students who have an intermediate proficiency in English and aim to achieve advanced language skills. This course focuses on refining and mastering the intricacies of English in reading, writing, listening, and speaking.",
                            Price = 800m,
                            ProductName = "English 301"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "English 401: Proficient Language Mastery is designed for students who have advanced proficiency in English and aspire to reach a near-native level of fluency. This course focuses on perfecting language skills in reading, writing, listening, and speaking through engagement with highly complex texts and sophisticated communication activities.",
                            Price = 1000m,
                            ProductName = "English 401"
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "German 101: Introduction to German Language is designed for beginners eager to start learning German. This course focuses on building foundational skills in reading, writing, listening, and speaking German. Students will learn basic vocabulary, essential grammar, and key phrases for everyday communication.",
                            Price = 500m,
                            ProductName = "German 101"
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "German 201: Intermediate German Language is designed for students who have a basic understanding of German and wish to enhance their proficiency. This course focuses on expanding vocabulary, refining grammar, and improving skills in reading, writing, listening, and speaking at an intermediate level.",
                            Price = 600m,
                            ProductName = "German 201"
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "German 301: Advanced German Language is designed for students who have intermediate proficiency in German and aim to reach a higher level of fluency. This course focuses on refining advanced language skills in reading, writing, listening, and speaking. ",
                            Price = 800m,
                            ProductName = "German 301"
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "German 401: Proficient German Language Mastery is designed for students who have advanced proficiency in German and strive for near-native fluency. This course focuses on perfecting language skills in reading, writing, listening, and speaking through engagement with highly complex texts and sophisticated communication activities.",
                            Price = 1000m,
                            ProductName = "German 401"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
